### ISSUE TITLE
Tracking issue for 1.5.0 release

### ISSUE THREAD

**Issue by jonasmalacofilho** [liquidctl/liquidctl#277]
# Release checklist

## Prepare repository

 - [x] Update liquidctl/version.py
 - [x] Update last update data in the man page
 - [x] Make sure the CHANGELOG is up to date
 - [x] Update the link in the README to the stable executable for Windows
 - [x] Remove "N/New driver, ..." notes from the table of supported devices
 - [x] Commit "release: prepare for v<version>"

## Test

_with `"$(liquidctl --version) = "liquidclt v<version>"`:_

 - [x] Run unit and doc tests: `pytest`
 - [x] Run my setup scripts: `liquidcfg && liquiddyncfg`
 - [x] Run old HW tests: `extra/old-tests/asetek_*` and `extra/old-tests/kraken_two`
 - [x] Test krakenduty: `extra/krakenduty-poc train && extra/krakenduty-poc status`
 - [x] Test krakencurve: `extra/krakencurve-poc control --fan-sensor coretemp.package_id_0 --pump '(25,50),(35,100)' --fan '(25,35),(35,60),(60,100)' --verbose`
 - [x] Test yoda: `extra/yoda --match kraken control pump with '(20,50),(50,100)' on coretemp.package_id_0 and fan with '(20,25),(34,100)' on _internal.liquid --verbose`
 - [x] Test liquiddump: `extra/liquiddump | jq -c .`
 - [x] Test krakenx (git): `colctl --mode fading --color_count 2 --color0 192,32,64 --color1 246,11,21 --fan_speed "(30, 100), (40, 100)" --pump_speed "(30, 100), (40, 100)"`

## Source distribution

 - [x] Tag HEAD with `git tag -as v<version>` and short summary annotation (signed)
 - [x] Push HEAD and `v<version>` tag
 - [x] Check all CI statuses (pytest, flake8 linting, and `list --verbose`)
 - [x] Generate the source distribution: `python setup.py sdist`
 - [x] Check that all necessary files are in `dist/liquidctl-<version>.tar.gz` and that generated `extraversion.py` makes sense
 - [x] Sign the source distribution: `gpg --detach-sign -a dist/liquidctl-<version>.tar.gz`

## Binary distribution for Windows

 - [x] Download and check artifact built by AppVeyor
 - [x] Sign the artifact: `gpg --detach-sign -a dist/liquidctl-<version>-bin-windows-x86_64.zip`

## Release

 - [x] Upload: `twine upload dist/liquidctl-<version>.tar.gz{,.asc}`
 - [x] Upgrade the `v<version>` tag on GitHub to a release (with sdist, Windows artifact, and corresponding GPG signatures)
 - [x] Update the HEAD changelog with the release file SHA256 sums

## Post release

 - [x] Merge the release branch into the main branch
 - [x] Update the HEAD release-checklist with this checklist
 - [x] Update ArchLinux `liquidctl-git`
